### ISSUE TITLE
error while running examples

### ISSUE THREAD

**Issue by varunvenna** [dfki-ric-underactuated-lab/double_pendulum#2]
```
$ python3 pid_traj.py
/double_pendulum/lib/python3.10/site-packages/double_pendulum/simulation/simulation.py:1063: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
[0.0]
[[0.0, 0.0, -7.37344695478681e-05, -0.000171805470714]]
[]
Traceback (most recent call last):
  File "/home/venvli/double_pendulum/examples/ideal/pid_traj.py", line 60, in <module>
    plot_timeseries(T, X, U,
  File "/home/venvli/double_pendulum/lib/python3.10/site-packages/double_pendulum/utils/plotting.py", line 213, in plot_timeseries
    T[: len(U)], np.asarray(U).T[0, : len(T)], label=r"$u_1$", color="blue"
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by fwiebe** [comment]
Hi @varunvenna , 
the problem is that your matplotlib is using a non-GUI backend (see the warning after your command). If you would like to see the animation switch to a gui backend e.g. with

  import matplotlib
  matplotlib.use('TkAgg')

If you want to simulate the double pendulum without animation you can use the sim.simulate(...) function which is commented below the sim.simulate_and_animate(...) function in the pid_traj.py script you are testing.

**Comment by varunvenna** [comment]
okay. thank you!
The problem is resolved by just installing python3-tk
```bash
sudo apt-get install python3-tk
```
